# Refs: https://github.com/boostorg/boost/issues/996
def find_and_replace_boost_url
  pod_spec = "../node_modules/react-native/third-party-podspecs/boost.podspec"
  puts "Debug: Starting boost URL replacement"
  if File.exist?(pod_spec)
    puts "Debug: Found boost.podspec"
    spec_content = File.read(pod_spec)
    spec_content.gsub!(
      'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
      'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
    )
    File.write(pod_spec, spec_content)
    puts "Debug: Updated boost.podspec"
  end
end

find_and_replace_boost_url

platform :ios, '12.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RNDemo' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'AmazonChimeSDK', '0.27.2'
  pod 'AmazonChimeSDKMedia', '0.25.2'

  target 'RNDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    legacy_cpp_targets = ['RCT-Folly']
    installer.pods_project.targets.each do |target|
      uses_legacy_cpp = legacy_cpp_targets.include?(target.name) || target.name.start_with?('Flipper')
      next unless uses_legacy_cpp

      target.build_configurations.each do |config|
        # Keep legacy Folly/Flipper code on a compatible C++ standard with modern Xcode.
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'

        if target.name.start_with?('Flipper')
          other_cxx_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          unless other_cxx_flags.include?('-include functional')
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{other_cxx_flags} -include functional"
          end
        end
      end
    end
  end
end
